name: Build
run-name: Manual build 🔨
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-project:
    name: Build 🧱
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
    permissions:
      contents: read
